### ISSUE TITLE
v3 is broken after key is not given anymore in params

### ISSUE THREAD

**Issue by aiomaster** [jkraemer/redmine_airbrake#2]
We have trouble using the newest `airbrake-ruby` gem cause the `project_key` is not send anymore as key param to the airbrake server.
See this commit: https://github.com/airbrake/airbrake-ruby/commit/5d258a28993ca2b2649e02abd93dfa944f207063

So the redmine_airbrake throws a 500 in the controller, cause there is no param `key` here:
https://github.com/jkraemer/redmine_airbrake/blob/6febdad0544945dab81d16abd4bef9fb1f576f6d/app/controllers/airbrake_notices_controller.rb#L43

It seems the project_key is not made for transmitting all the information the `redmine_airbrake` plugin needs.

We monkey patched our airbrake client to make it work, but it is really ugly.
```
  module Patches
    module Airbrake
      module Config
         def endpoint
           @endpoint ||=
             begin
               redmine_params =
                 CGI.escape({
                   tracker: 'Exception',
                   api_key: 'foo',
                   project: 'bar',
                   assigned_to: 'developer'
                 }.to_json)
               super + "?key=#{redmine_params}"
             end
         end
      end
    end
  end

  Airbrake::Config.prepend(::Patches::Airbrake::Config)
```
One solution could be to implement a new config option in `airbrake-ruby` to give custom parameters to the url. Another option would be to post these informations as json in the request body with all other informations and patch the controller to read it from there.
What would you think?

Greetings from DD! ;)

**Comment by jkraemer** [comment]
Hi :)

I think the proper solution would be to handle this case and grab the serialized data (aka project key) from the Authorization header if no key param is present. I'm not sure about potential length limits in http headers but if we're lucky we can continue abusing this value as we did before.

I can have a look at that but almost certainly not before Christmas...

Cheers!

**Comment by jkraemer** [comment]
On a sidenote - why you cannot simply use a slightly older version of airbrake-ruby? :)

**Comment by aiomaster** [comment]
Yeah, just use an older version is an option, but I am not a friend of this, cause you shift the problem to the future when you have to upgrade, cause some other dependencies forces you.

I just don't understand why there is this abuse of the `project_key` and maybe there could be a better option to provide additional information to the request.
If it could be part of the json request body there would be no potential length limits like in HTTP headers and it could get parsed with the rest of the body, so we don't need to mess around with `CGI.escape` and that stuff. The downside is, that a change in `airbrake-ruby` is required and we need a custom key that is not used in the rest of the airbrake json schema. Maybe the key could be configurable.

**Comment by aiomaster** [comment]
Hi @jkraemer,
maybe it could be a lot easier to include the additional redmine parameters in the json body of the notice.
We could for example do the following in our airbrake initializer:
```ruby
Airbrake.add_filter do |notice|
  notice[:redmine] = {
    tracker: 'Exception',
    api_key: 'foo',
    project: 'bar',
    assigned_to: 'developer'
  }
end
```
Then we have to extract the config information after parsing the request body. This seems like a clean solution to me. What do you think? Should I make a PR for this?

**Comment by jkraemer** [comment]
Thanks for the idea with the filter, that's what I implemented now as the default way to configure this. `notice[:redmine]` didn't work though, I chose `notice[:context][:redmine_config]`.

Greetings from the Philippines :)
