### ISSUE TITLE
error class but no line in issue title when using with airbrake-ruby 2.9+

### ISSUE THREAD

**Issue by eiapopeia** [jkraemer/redmine_airbrake#3]
Since _airbrake-ruby_ 2.9 this gem only writes the error class in title of the issue. So there is
```
RuntimeError
```
instead of
```
RuntimeError in app/controllers/application_controller.rb:12
```

This is because  the backtrace of _airbrake-ruby_ does not contain `[PROJECT_ROOT]/some/path:12` but `/PROJECT_ROOT/some/path:12`. See https://github.com/airbrake/airbrake-ruby/pull/311/commits/d6e3855a66a104162ba1beba3f1da559a80130bd for details.

**Comment by jkraemer** [comment]
merged the PR
