### ISSUE TITLE
suggest disabling of airbrake performance monitoring

### ISSUE THREAD

**Issue by aiomaster** [jkraemer/redmine_airbrake#5]
Hi,

`airbrake-ruby` has a new performance monitoring feature since version 4.5.0, which is enabled by default. (see their changelog: https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md )
This causes trouble with the redmine_airbrake plugin, cause it can not handle these requests and throws tons of exceptions. (both in the app and in the redmine log).

The feature can be simply disabled by setting:
```ruby
Airbrake.configure do |config|
  # ...
  config.performance_stats = false
  config.query_stats = false
end
```
Maybe it would be helpfull for others if you suggest these options in your README.
I don't think we could really use these performance monitoring things to generate issues in redmine or something or do you have an idea?

Thanks and Greets!

**Comment by jkraemer** [comment]
Thank you!
